project:
  type: website

website:
  title: "Urban Sensing With Satellites - Jurong Lake District"
  navbar:
    
    background: "#557153"

    right:
      - href: index.qmd
        text: Home
      - href: data_preparation.html
        text: Data Preparation
      - href: analysis.html
        text: Analysis
      - href: poster.html
        text: Poster
      - href: documentation.html
        text: Documentation
      - href: about.html
        text: About The Team

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: visual

